name: mexyou
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  http: ^0.12.0+2
  encrypt: ^3.3.1
  crypto: ^2.1.3
  dio: ^3.0.4
  flutter_svg: ^0.14.4
  provider: ^3.1.0+1
  cached_network_image: ^2.0.0-rc
  hydrated_bloc: ^2.0.0
  flutter_bloc: ^2.0.0
  page_transition: ^1.1.5
  url_launcher: ^5.2.5
  sembast: ^2.1.0+1
  auto_size_text: ^2.1.0
  functional_widget: ^0.7.1
  cupertino_back_gesture: ^0.0.1
  cupertino_icons: ^0.1.2
  shimmer: ^1.0.0
  flutter_spinkit: ^4.0.0
  swipe_stack: ^1.0.0
  built_value:
  built_collection:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build:
  build_config:
  built_value_generator:
  json_serializable: ^3.0.0
  build_runner: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/bg.png
    - assets/images/selfies.png
    - assets/images/share_location.png
  fonts:
    - family: MYIcons
      fonts:
        - asset: assets/fonts/MYIcons/MYIcons.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy/Gilroy-UltraLight.ttf
          weight: 100
        - asset: assets/fonts/Gilroy/Gilroy-Thin.ttf
          weight: 200
        - asset: assets/fonts/Gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy/Gilroy-Black.ttf
          weight: 900
